name: update manifest
on:
  schedule:
    - cron:  '* * 1 * *'
  workflow_dispatch:
jobs:
  update-manifest:
    runs-on: ubuntu-latest
    name: 'manifest-updater'
    steps:
      - uses: actions/checkout@v2
      - name: latest manifest updater     
        run: |
         .\updater.ps1 
jobs:
  update-manifest:
    runs-on: ubuntu-latest
    name: 'manifest-updater'
    steps:
      - uses: actions/checkout@v2
      - name: latest manifest updater        
        run: echo "This step will always run"
