name: update manifest
on:
  schedule:
    - cron:  '* * 1 * *'
  workflow_dispatch:
jobs:
  update-manifest:
    runs-on: ubuntu-latest
    name: 'manifest-updater'
    steps:
      - uses: actions/checkout@v2
      - name: latest manifest updater 
        shell: pwsh
        run: |
         .\updater.ps1 
